//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSE445_Assignment5.CelebBirthdaySVC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CelebBirthdaySVC.ICelebBirthday")]
    public interface ICelebBirthday {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICelebBirthday/bornOn", ReplyAction="http://tempuri.org/ICelebBirthday/bornOnResponse")]
        string[] bornOn(string date, int outputNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICelebBirthday/bornOn", ReplyAction="http://tempuri.org/ICelebBirthday/bornOnResponse")]
        System.Threading.Tasks.Task<string[]> bornOnAsync(string date, int outputNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICelebBirthdayChannel : CSE445_Assignment5.CelebBirthdaySVC.ICelebBirthday, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CelebBirthdayClient : System.ServiceModel.ClientBase<CSE445_Assignment5.CelebBirthdaySVC.ICelebBirthday>, CSE445_Assignment5.CelebBirthdaySVC.ICelebBirthday {
        
        public CelebBirthdayClient() {
        }
        
        public CelebBirthdayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CelebBirthdayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CelebBirthdayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CelebBirthdayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] bornOn(string date, int outputNumber) {
            return base.Channel.bornOn(date, outputNumber);
        }
        
        public System.Threading.Tasks.Task<string[]> bornOnAsync(string date, int outputNumber) {
            return base.Channel.bornOnAsync(date, outputNumber);
        }
    }
}
